### ISSUE TITLE
How to change "xlink:href"

### ISSUE THREAD

**Issue by musatarosu335** [hugozap/react-svgmt#1]
Hi,
Thank you for a great tool.

Now, I want to change the `xlink:href` attribute of` <image> `by using` <SvgProxy> `.
I coded it as follows, but it was not the correct behavior. (`url` contains the path to the image)
```jsx
<SvgProxy
    selector="#Image image"
    xlinkHref={url}
/>
```
How can I modify `xlink:href` ?

Thank you.

**Comment by hugozap** [comment]
good catch, fixed in v1.1.2  (will add to docs soon). The way to update a namespaced attribute is:
`
<SvgProxy
    selector="#Image image"
    xlink_href={url}
/>
`

Let me know if you have any issue with it

**Comment by musatarosu335** [comment]
I am amazed at the prompt response.

It worked perfectly.
Thank you!

**Comment by hugozap** [comment]
cool! I'm curious about projects using this library, so let me know if you build something cool with it.

**Comment by musatarosu335** [comment]
OK!
I will publish it when I make something :-)
