### ISSUE TITLE
Gradients missing

### ISSUE THREAD

**Issue by dreadjesus** [hugozap/react-svgmt#12]
Hi. 
I'm not sure where the issues are originating from but im using photoshop and then convert it to an svg. 

Looking at the svg in regular progrms it looks fine and all gradients are correct. But when i load it to react i lose some gradient information. 
(diffrent information is lost in safari and chrome as well) 

any ideas?

**Comment by hugozap** [comment]
What happens if you open the SVG directly with the browsers?

**Comment by dreadjesus** [comment]
Hi. 
It works well. I ended up using https://svg2jsx.com/ to convert it and inserting the props instead. 
Really like the idea, would be amazingly helpful when working with svgs and still are for lots of stuff. 

Just that it didn't really manage to keep the background and stuff like that for safari is a bit to big of an issue.

best regards 
R

**Comment by hugozap** [comment]
Glad that you solved it.
If possible could you share a sample SVG so I can reproduce the problem? It
may benefit someone else in the future, thanks!

**Comment by dreadjesus** [comment]
i removed the trees from the svg but i think you can find the common polygons, you see the issue in the print screen. 
Hope it helps and give me a shoutout if you solve it:) 

<img width="1328" alt="Screenshot 2019-08-23 at 22 45 58" src="https://user-images.githubusercontent.com/22561634/63622715-d012d580-c5f7-11e9-8d9c-57b018e63e01.png">
[sample-gradients-svg.zip](https://github.com/hugozap/react-svgmt/files/3536137/sample-gradients-svg.zip)

**Comment by fabiougolini** [comment]
Hi, I have the same issue. Is there a solution to avoid using JSX converter? It would be much easier to use the native SVG so if you need to modify it you don't need everytime to reconvert it to JSX..

Thanks!
