### ISSUE TITLE
Warning not given when SVG is missing file extension

### ISSUE THREAD

**Issue by m-weeks** [hugozap/react-svgmt#13]
Just ran into this issue, when my URL did not end in .svg, it doesn't load, but it also doesn't provide any sort of warning.

I noticed this in the code:
```
      // We can only inject SVG
      if (!/\.svg/i.test(imgUrl)) {
        callback(
          'Attempted to inject a file with a non-svg extension: ' + imgUrl
        );
        return;
      }
```
but this message doesn't ever seem to be provided to the developer

**Comment by hugozap** [comment]
Hi,  I removed the validation so all url's should work now 6cc99ea2991c914499a4753eff15e3d02f874095
