### ISSUE TITLE
Multiple Proxies for one Element

### ISSUE THREAD

**Issue by strudelbeast** [hugozap/react-svgmt#16]
Greeting,

I have a svg-file with polygons inside and I want to have a proxy for all polygons to call a method and another one to color some of them.

```
render() {
    return <SvgLoader path={'raumplan.svg'}>
      {
        this.props.store.visitorStore.booths.map((booth, index) => {
          return <SvgProxy key={booth.id} selector={`#${booth.roomnumber} polygon`} onClick={this.doAction} />
        }),
        this.props.store.visitorStore.visitedBooths.map((booth, index) => {
          return <SvgProxy key={booth.id} selector={`#${booth.roomnumber} polygon`} style='fill: #9cce2b' />
        })
      }
      )}
    </SvgLoader>
  }
```

But always just the second one works

Thanks for help in advance.

**Comment by hugozap** [comment]
The first Proxy needs a selector, also make sure the key prop is unique
(duplicated keys will make one of them invalid)

**Comment by strudelbeast** [comment]
I have a selector at the first proxy, doesn't I? Does the selector also have to be unique or how can I manage to make my thouths work?

**Comment by hugozap** [comment]
Try adding a different prefix to your key props e.g key={'action'+booth.id} and key={'styles'+booth.id}

**Comment by strudelbeast** [comment]
That doesn't change anything

![image](https://user-images.githubusercontent.com/22666594/67980652-341cd000-fc1f-11e9-92f9-88a8a3033eb4.png)

Is maybe the warning a problem? I'm pretty new to react.

**Comment by strudelbeast** [comment]
So thanks a lot. I just figured out that I just have to replace the , by a }{
