### ISSUE TITLE
SvgProxy populated by dynamic array don't change

### ISSUE THREAD

**Issue by c-malecki** [hugozap/react-svgmt#21]
I hope I explain this succinctly enough.

I'm using an array, `mapData`, to create a `<SvgProxy>` for each entry within the `mapData` array. 
```
const { mapData } = this.props;
    return (
      <div className="DistrictMaps_Container">
        <SvgLoader path={DistrictsMap}>
          {mapData.map((data) => (
              <SvgProxy
                key={`#${data.district}`}
                selector={`#${data.district}`}
                fill={this.genColor(data.rate)}
                onClick={() => this.handleUpdateMapInfoDisplay(data)}
              />
          ))}
        </SvgLoader>
      </div>
```
The fill prop of the `<SvgProxy>`s use a helper method, `genColor()` that returns a color based on a `rate` property within each element of the `mapData` array. 
e.g.:  ```if (rate <= 0) {
      return "#cccccc"```

This works correctly for populating the initial svg map coloring and properties from the `<SvgProxy>`s. 

The issue I'm facing is when `mapData` is dynamically changed by a range slider, adding or removing elements within the array, it doesn't appear that `<SvgProxy>`s are also added or removed based on `mapdata` and the map coloration doesn't change.

My thoughts are that this isn't triggering a rerender for some reason since the `mapData` prop change only affects the `<SvgProxy>s` within the `<SvgLoader>`? Or is there something more to it that would essentially reset/remove all `<SvgProxy>`s and then re-add them based on the new `mapData` array?

Thank you!

**Comment by hugozap** [comment]
Take a look at this example: https://codesandbox.io/s/7w81wm0z11?file=/src/index.js
It starts with an array that's used to select some elements and if you click the "change selection" button it will change the color of other elements.

The key is that there's a reset SvgProxy that always set the color to black for every element, so all elements get resetted before other SvgProxies are applied.

**Comment by c-malecki** [comment]
Amazing. That was the fix I needed. Thank you very much. I will definitely revisit and explore this library much more after getting the feature work done currently for the app it's being used it.
