### ISSUE TITLE
Update text in SVG

### ISSUE THREAD

**Issue by Henna1977** [hugozap/react-svgmt#25]
Hello,
I try to update a text on an SVG with this component and have some problems.
With a static text everything is fine, but when I try to set a dynamic text the value will be ignored.

I paste the code below.

Can someone confirm the problem, or am I misusing the component?

```
import testimg from './img/test.svg';

  render() {
    return (
      <div>
        <h2> Image Update</h2>
        <SvgLoader path={testimg}>
           // 'static Text' is shown correct
          <SvgProxy selector="#txt_1">static Text</SvgProxy>  
          // 'initial Text' is shown not the dynamic value
          <SvgProxy selector="#txt_2">{this.props.txtvalue} </SvgProxy>
        </SvgLoader>
        // value is shown correct
        {this.props.txtvalue}
      </div>

    );
  }
```

**Comment by hugozap** [comment]
Hi, could you post the svg file you are using?

I created a test codesandbox to update text values from the state and it's working fine.

https://codesandbox.io/s/reactsvgmt-dynamic-text-u5s3c

**Comment by hugozap** [comment]
With text, if the svg has tspans you have to target those with the selector. Not sure if this may be your problem.
