### ISSUE TITLE
How to use SVG sprites with react-svgmt?

### ISSUE THREAD

**Issue by fasola81** [hugozap/react-svgmt#28]
Hi guys, this may be a silly question, but i cant figure this out on my end. Can you please help me understand how i can use this component with [svg sprites](https://medium.com/@gineetmehta/how-to-use-svg-sprites-regular-html-vs-react-9f98948c03f0)?

For reference, this is what i would like to do:
```
<SvgLoader svgXML={this.state.svg} width="20%" use="#sprite1">
</SvgLoader>
```

**Comment by hugozap** [comment]
Hi Michal, you need to add the <use> element to the SVG so you can use an SvgProxy to target it and modify it.

**Comment by fasola81** [comment]
thanks, that worked.
