### ISSUE TITLE
Not working on IE11

### ISSUE THREAD

**Issue by Jeerjmin** [hugozap/react-svgmt#4]
On Chrome, Safari, Firefox - good.
There are no errors in the console, but they are not displayed.

I've tried to use babel-polyfill, no luck.

What can be wrong ?

**Comment by hugozap** [comment]
I did a quick test on IE and this line throws an error ( using Array.from is not supported ) 
https://github.com/hugozap/react-svgmt/blob/7bfdf1aa2463fecb506b32e79038ee859d33d6af/src/svg-proxy.js#L48

I can't work on it right now, but if you want to send a PR I can merge and push the new version

**Comment by hugozap** [comment]
hey @Jeerjmin I changed the line to a IE11 compatible syntax and pushed a new version. I don't have a windows setup and can't test on IE11 right now but if you can, let me know if it works or there are additional issues.

**Comment by usualpro** [comment]
Hello @hugozap , I've got the same issue here.
The svg tag in the dom is empty when using IE11. Any idea on how to fix that ?

**Comment by hugozap** [comment]
Hi @usualpro , I think I know what's the issue here as commented [before](https://github.com/hugozap/react-svgmt/issues/4#issuecomment-401571090) I'll be able to look into it later today but if you want to try locally just replace line 48 in svg-proxy.js with a IE11 compatible syntax , rebuild and point your app to the local repo. If that works you can send the PR for me to merge.

**Comment by usualpro** [comment]
Hello @hugozap, thanks again:
I finally do something like that:
```
npm install raw-loader --save
/* eslint import/no-webpack-loader-syntax: off */
import Img from '!raw-loader!./img/img.svg';
<div dangerouslySetInnerHTML={(() => ({ __html: Img }))()} />
```

**Comment by alimafilho** [comment]
Hello @hugozap , svg still does not appear in ie11. Svg loads, but does not render the component. There are no errors in the console, just this message:
HTML1300: Navigation occurred

Any tips on which file to debug?

**Comment by flogy** [comment]
After replacing all occurences of `[].includes(something)` with IE11 compatible `[].indexOf(something) !== -1` there were no more incompatibilities with the JS code. However, the SVG was still not displayed. This time without any console errors.

@usualpro were you able to manipulate the SVG with your inclusion method? Or is this just a fallback to `<img src="image.svg" />`?

**Comment by usualpro** [comment]
> After replacing all occurences of `[].includes(something)` with IE11 compatible `[].indexOf(something) !== -1` there were no more incompatibilities with the JS code. However, the SVG was still not displayed. This time without any console errors.
> 
> @usualpro were you able to manipulate the SVG with your inclusion method? Or is this just a fallback to `<img src="image.svg" />`?

Hi @flogy , yes.

**Comment by Odrin** [comment]
https://github.com/hugozap/react-svgmt/blob/81a981fbda944d25eba36618ffdec17c847ab425/src/svg-injector.js#L324
IE11 doesn't support `innerHTML` prop, it's `undefined` in IE.
I use simple workaround:
```js
function getSvgContent(svg) {
  const serializer = new XMLSerializer();

  return Array.from(svg.childNodes).map(node => serializer.serializeToString(node));
}
```

**Comment by enekesabel** [comment]
I was able to fix this issue based on @Odrin's workaround and this fiddle: [https://jsfiddle.net/microbians/8ztNU/](url)

PR is available here: https://github.com/hugozap/react-svgmt/pull/11

**Comment by hugozap** [comment]
This is awesome, thanks @enekesabel. The PR is merged now.
