### ISSUE TITLE
How to set transform properties?

### ISSUE THREAD

**Issue by Ziriax** [hugozap/react-svgmt#6]
How can I update the `transform` property of an SVG element?

In my DOM manipultation code I would write:

```
  const rotation = numberEditor.createSVGTransform();
  rotation.setRotate(
    degrees,
    knobBox.x + knobBox.width / 2,
    knobBox.y + knobBox.height / 2
  );
  knobGroup.transform.baseVal.initialize(rotation);
```

But how can I do this with an `SvgProxy`? I could of course use the `onElementSelected`  callback, and do DOM manipulation, but that feels wrong here.

Thanks!

**Comment by hugozap** [comment]
Because with a proxy you are updating the svg node, you should create the appropiate svg transform string and then just set it as an attribute of the SvgProxy element.

```
const t = `translate(${x}, ${y})`
...
<SvgProxy ... transform={t} />
```

**Comment by Ziriax** [comment]
Ah so it is really updating the attributes, just like you would call `setAttribute`. 

Does it also contain a minimal update mechanism, like React, or does it just copies all the attributes whenever any changes (might be faster these days with modern browsers than checking what changes in JS, no idea).

Thanks a lot for the feedback.

**Comment by hugozap** [comment]
Yes it will directly update the svg node setting it's attributes from the proxy props.
Right now when a proxy prop changes it will update all the attributes declared.  It will only update the svg element that changed.  Overall it's fast.

**Comment by hugozap** [comment]
Let me know if you build something cool with it!
