### ISSUE TITLE
Warning: Unsafe lifecycle

### ISSUE THREAD

**Issue by nufaylr** [hugozap/react-svgmt#7]
Im getting an unsafe lifecycle method warning under Strict Mode while using SvgProxy component.  see the following react lifecycle depreciation message 

[UNSAFE_componentWillReceiveProps](https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops)

``` js
Warning: Unsafe lifecycle methods were found :
componentWillReceiveProps: Please update the following 
components to use static 
getDerivedStateFromProps instead: SvgProxy
```

Usage at : 

https://github.com/hugozap/react-svgmt/blob/81a981fbda944d25eba36618ffdec17c847ab425/src/svg-proxy.js#L32

**Comment by hugozap** [comment]
Hi @nufaylr I think its time to refactor componentWillReceiveProps out.  Will take a look and update this issue when done.

**Comment by hugozap** [comment]
@nufaylr I updated it to use cdu instead of cwrp. Fixed on latest published version. Please update and let me know if you have any issues, thanks for the report!

**Comment by nufaylr** [comment]
Hey @hugozap Just updated the version into latest, and now warning message is disappeared 👍 
Many thanks
